let DATA=null,REG=null,map=null,boundaryGeo=null,boundaryLayer=null;
const moneyM=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n*1e6);
const moneyB=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n*1e9);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const el=id=>document.getElementById(id);
const colorFor=(key)=>{let h=0;for(const c of key)h=(h*31+c.charCodeAt(0))%360;return `hsl(${h},55%,45%)`};
async function getJSON(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(`${url} HTTP ${r.status}`);return r.json()}
async function load(){try{[DATA,REG]=await Promise.all([getJSON("./data/public-data.json"),getJSON("./data/regions.json")]);buildFilters();initMap();bind();render();renderSources();renderCoverage();renderHierarchy();await loadBoundaries()}catch(e){el("mapError").classList.remove("hidden");el("mapError").textContent="Data utama gagal dimuat: "+e.message;el("boundaryStatus").textContent="BOUNDARY: GAGAL"}}
function initMap(){map=L.map("map").setView([0.65,122.65],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);setTimeout(()=>map.invalidateSize(true),200)}
function buildFilters(){updateRegionOptions();el("level").addEventListener("change",()=>{updateRegionOptions();render();renderHierarchy()})}
function updateRegionOptions(){const level=el("level").value,s=el("region");let rows=[];if(level==="provinsi")rows=[{id:"75",name:"Provinsi Gorontalo"}];else if(level==="kabupaten_kota")rows=Object.entries(REG.kabupaten_kota).map(([id,x])=>({id,name:x.name}));else if(level==="kecamatan")rows=Object.entries(REG.kecamatan).map(([id,x])=>({id,name:x.name}));else if(boundaryGeo)rows=boundaryGeo.features.map(f=>{const p=f.properties||{};return{id:p.kdebps||p.kdepum||p.namobj,name:p.wadmkd||p.namobj||"Desa/Kelurahan"}}).filter(x=>x.id);const uniq=[...new Map(rows.map(x=>[x.id,x])).values()].sort((a,b)=>a.name.localeCompare(b.name,"id"));s.innerHTML='<option value="all">Semua wilayah</option>'+uniq.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("")}
function bind(){["year","focus","region","search"].forEach(id=>el(id).addEventListener(id==="search"?"input":"change",render));el("reset").onclick=()=>{el("year").value="2026";el("focus").value="apbd";el("level").value="provinsi";updateRegionOptions();el("region").value="all";el("search").value="";render();renderHierarchy()};el("download").onclick=()=>{const a=document.createElement("a"),b=new Blob([JSON.stringify(DATA,null,2)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download="gorontalo-public-data-monitor-public-snapshot.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}}
async function loadBoundaries(){const b=REG.boundary;try{const u=b.query_url+"?where="+encodeURIComponent(b.where)+"&outFields="+encodeURIComponent(b.out_fields)+"&returnGeometry=true&outSR=4326&f=geojson&resultRecordCount=1000";boundaryGeo=await getJSON(u);if(!boundaryGeo.features||boundaryGeo.features.length===0)throw new Error("0 feature");el("boundaryStatus").textContent=`BOUNDARY: ${boundaryGeo.features.length} FEATURE`;el("mapError").classList.add("hidden");updateRegionOptions();render();renderHierarchy()}catch(e){el("boundaryStatus").textContent="BOUNDARY: GAGAL";el("mapError").classList.remove("hidden");el("mapError").innerHTML=`<b>Polygon administratif tidak tersedia saat ini.</b><br>${esc(e.message)}<br><small>Data snapshot tetap aman; tidak ada geometri pengganti yang dibuat.</small>`}}
function props(f){return f.properties||{}}
function featureMatches(f,level,rid,q){const p=props(f),name=(p.wadmkd||p.namobj||"").toLowerCase(),search=q.toLowerCase();if(search&&!name.includes(search)&&!(p.wadmkc||"").toLowerCase().includes(search)&&!(p.wadmkk||"").toLowerCase().includes(search))return false;if(rid==="all")return true;if(level==="desa")return (p.kdebps||p.kdepum)===rid;if(level==="kecamatan")return (p.kdcbps||p.kdcpum)===rid;if(level==="kabupaten_kota")return (p.kdbbps||p.kdpkab)===String(rid).replace(".","");if(level==="provinsi")return true;return false}
function parentKey(f,level){const p=props(f);if(level==="desa")return p.kdebps||p.kdepum||p.namobj;if(level==="kecamatan")return p.kdcbps||p.kdcpum||p.wadmkc;if(level==="kabupaten_kota")return p.kdbbps||p.kdpkab||p.wadmkk;return "75"}
function renderMap(){if(!boundaryGeo||!map)return;const level=el("level").value,rid=el("region").value,q=el("search").value.trim();if(boundaryLayer)boundaryLayer.remove();const features=boundaryGeo.features.filter(f=>featureMatches(f,level,rid,q));boundaryLayer=L.geoJSON({type:"FeatureCollection",features},{style:f=>{const p=props(f),key=parentKey(f,level);return{color:"#111",weight:level==="desa"?0.6:1.2,fillColor:colorFor(String(key)),fillOpacity:level==="desa"?0.35:0.28}} ,onEachFeature:(f,l)=>{const p=props(f);l.bindPopup(`<b>${esc(p.wadmkd||p.namobj||"Desa/Kelurahan")}</b><br>${esc(p.wadmkc||"")} · ${esc(p.wadmkk||"")}<br><small>Kode desa: ${esc(p.kdebps||p.kdepum||"—")}</small>`);l.on("click",()=>{if(level!=="desa"){const target=level==="kabupaten_kota"?(p.kdbbps||p.kdpkab):level==="kecamatan"?(p.kdcbps||p.kdcpum):"all";if(target&&level!=="provinsi"){el("region").value=level==="kabupaten_kota"?String(target).replace(/^75/,'75.'):target;render()}}})}}).addTo(map);if(features.length){try{map.fitBounds(boundaryLayer.getBounds(),{padding:[12,12],maxZoom:12})}catch(e){}}el("mapSubtitle").textContent=`${features.length} polygon tampil · level ${labelLevel(level)}.`;el("mapLegend").innerHTML=`<span class="legend-dot" style="background:${colorFor(level)}"></span>${labelLevel(level)} · geometry berasal dari boundary desa/kelurahan 2025`}
function labelLevel(l){return l==="provinsi"?"Provinsi":l==="kabupaten_kota"?"Kabupaten/Kota":l==="kecamatan"?"Kecamatan":"Desa/Kelurahan"}
function setKpis(){const p=DATA.province.apbd_history["2026"],l=p.latest_change,y25=DATA.province.apbd_history["2025"].summary,t=DATA.province.tkdd_2024,a=DATA.aggregates.six_district_city_total_tkdd_2024;el("kpiRevenue").textContent=moneyB(p.initial.pendapatan.total/1e9);el("kpiExpense").textContent=moneyB(p.initial.belanja.total/1e9);el("kpiExpenseChange").textContent=moneyB(l.belanja);el("kpi2025Real").textContent=moneyB(y25.belanja_realization_billion);el("kpi2025Pct").textContent=y25.belanja_realization_pct+"% dari anggaran Rp"+y25.belanja_budget_billion.toLocaleString("id-ID")+" M";el("kpiTkdd").textContent=moneyM(a.realization_million);el("kpiTkddPct").textContent=a.realization_pct+"% dari anggaran "+moneyM(a.budget_million);el("kpiProvTkdd").textContent=moneyM(t.realization_million);el("kpiProvTkddPct").textContent=t.realization_pct+"% dari anggaran "+moneyM(t.budget_million);el("kpiDatasets").textContent=DATA.open_data.catalog.province_datasets+"+"}
function render(){if(!DATA)return;setKpis();const y=el("year").value,f=el("focus").value,rid=el("region").value,q=el("search").value.trim().toLowerCase();renderSummary(y,f,rid,q);renderApbd(y);renderDistricts(q);renderLatest(q);renderMap();renderBreadcrumbs();}
function renderBreadcrumbs(){const level=el("level").value,rid=el("region").value;let html=`<span>Gorontalo</span>`;if(level!=="provinsi"&&rid!=="all"){if(level==="kabupaten_kota"){html+=`<b>›</b><span>${esc(REG.kabupaten_kota[rid]?.name||rid)}</span>`}else if(level==="kecamatan"){const x=REG.kecamatan[rid];html+=`<b>›</b><span>${esc(REG.kabupaten_kota[x?.parent_id]?.name||"")}</span><b>›</b><span>${esc(x?.name||rid)}</span>`}else if(level==="desa"&&boundaryGeo){const f=boundaryGeo.features.find(x=>featureMatches(x,"desa",rid,""));const p=f&&props(f);if(p)html+=`<b>›</b><span>${esc(p.wadmkk||"")}</span><b>›</b><span>${esc(p.wadmkc||"")}</span><b>›</b><span>${esc(p.wadmkd||p.namobj||rid)}</span>`}}el("breadcrumbs").innerHTML=html}
function renderSummary(y,f,rid,q){let html="";if(f==="latest"){el("summarySubtitle").textContent="Indikator terbaru dari Open Data Gorontalo.";html=DATA.open_data.latest_indicators.filter(x=>!q||x.name.toLowerCase().includes(q)).slice(0,8).map(x=>`<div class="summary-row"><span>${esc(x.name)}</span><strong>${esc(x.value)} ${esc(x.unit)}</strong></div>`).join("")}else if(f==="tkdd"){el("summarySubtitle").textContent="TKDD 2024 — DJPK/SIKD.";const a=DATA.aggregates.six_district_city_total_tkdd_2024;html=`<div class="summary-row"><span>6 kabupaten/kota</span><strong>${moneyM(a.budget_million)}</strong></div><div class="summary-row"><span>Realisasi</span><strong>${moneyM(a.realization_million)}</strong></div><div class="summary-row"><span>Persentase</span><strong>${a.realization_pct}%</strong></div>`}else{el("summarySubtitle").textContent="APBD Provinsi Gorontalo "+y+".";if(y==="2026"){const p=DATA.province.apbd_history["2026"];html=`<div class="summary-row"><span>Pendapatan awal</span><strong>${moneyB(p.initial.pendapatan.total/1e9)}</strong></div><div class="summary-row"><span>Belanja awal</span><strong>${moneyB(p.initial.belanja.total/1e9)}</strong></div><div class="summary-row"><span>Belanja perubahan terbaru</span><strong>${moneyB(p.latest_change.belanja)}</strong></div>`}else if(y==="2025"){const s=DATA.province.apbd_history["2025"].summary;html=`<div class="summary-row"><span>Pendapatan</span><strong>${moneyB(s.pendapatan_realization_billion)}</strong></div><div class="summary-row"><span>PAD</span><strong>${moneyB(s.pad_realization_billion)}</strong></div><div class="summary-row"><span>Belanja terealisasi</span><strong>${moneyB(s.belanja_realization_billion)}</strong></div>`}else{const rows=DATA.province.apbd_history[y]?.rows||[],r=rows.find(x=>x[0]==="Belanja Daerah");if(r)html=`<div class="summary-row"><span>Belanja Daerah</span><strong>${moneyM(r[1])} → ${moneyM(r[2])}</strong></div><div class="summary-row"><span>Realisasi</span><strong>${r[3]}%</strong></div>`}if(y==="2026"&&DATA.live_context){const c=DATA.live_context.djpb_regional_consolidated_may_2026;html+=`<div class="summary-row"><span>APBD konsolidasi regional s.d. Mei 2026</span><strong>${moneyB(c.belanja_realization_billion/1000)} (${c.belanja_realization_pct}%)</strong></div>`}}el("summary").innerHTML=html||'<p>Tidak ada data yang cocok.</p>';el("scopeNote").textContent=el("level").value==="provinsi"?"Level provinsi: angka fiskal berasal dari record provinsi." : "Level geografis dipilih. V3 tidak menurunkan total provinsi/kabupaten ke child tanpa geographic scope pada sumber."}
function renderApbd(y){const rows=[];if(y==="2026"){const p=DATA.province.apbd_history["2026"];rows.push(["2026","Pendapatan awal",p.initial.pendapatan.total/1e9,"Belum ada realisasi provinsi di snapshot","—","Perda 8/2025"],["2026","Belanja awal",p.initial.belanja.total/1e9,"Belum ada realisasi provinsi di snapshot","—","Perda 8/2025"],["2026","Pendapatan APBD-P terbaru",p.latest_change.pendapatan,"Angka perubahan dilaporkan","—","Laporan perubahan"],["2026","Belanja APBD-P terbaru",p.latest_change.belanja,"Angka perubahan dilaporkan","—","Laporan perubahan"])}else if(y==="2025"){const s=DATA.province.apbd_history["2025"].summary;rows.push(["2025","Pendapatan",s.pendapatan_target_billion/1000,s.pendapatan_realization_billion/1000,s.pendapatan_realization_pct+"%","Realisasi 2025"],["2025","PAD",s.pad_target_billion/1000,s.pad_realization_billion/1000,s.pad_realization_pct+"%","Realisasi 2025"],["2025","Belanja Daerah",s.belanja_budget_billion/1000,s.belanja_realization_billion/1000,s.belanja_realization_pct+"%","Realisasi 2025"])}else if(y==="2022"){rows.push(...DATA.province.apbd_history["2022"].rows.map(r=>[y,r[0],r[1],r[2],r[3]+"%","DJPK/SIKD"]))}el("apbdBody").innerHTML=rows.map(r=>`<tr><td>${r[0]}</td><td>${esc(r[1])}</td><td>${moneyB(r[2])}</td><td>${typeof r[3]==="number"?moneyB(r[3]):esc(r[3])}</td><td>${r[4]}</td><td>${esc(r[5])}</td></tr>`).join("")}
function renderDistricts(q){const rs=DATA.regions.filter(r=>!q||r.name.toLowerCase().includes(q));el("districtBody").innerHTML=rs.map(r=>`<tr><td>${esc(r.name)}</td><td>${moneyM(r.budget_million)}</td><td>${moneyM(r.realization_million)}</td><td>${r.realization_pct}%</td><td><a target="_blank" rel="noopener" href="${r.source}">DJPK ↗</a></td></tr>`).join("")}
function renderLatest(q){const rs=DATA.open_data.latest_indicators.filter(x=>!q||x.name.toLowerCase().includes(q));el("latestIndicators").innerHTML=rs.map(x=>`<div class="indicator"><b>${esc(x.name)}</b><span>${esc(x.value)} ${esc(x.unit)}</span><small>${esc(x.period)}</small></div>`).join("")||"<p>Tidak ada indikator yang cocok.</p>"}
function renderCoverage(){el("coverage").innerHTML=DATA.coverage.map(x=>{const bad=/not|pending|belum|gagal|tidak/i.test(x.status);return`<div class="coverage ${bad?"pending":"ok"}"><b>${esc(x.area)}</b><span>${esc(x.status)}</span><small>${esc(x.source)}</small></div>`}).join("")}
function renderSources(){el("sources").innerHTML=DATA.sources.map(s=>`<a class="source-card" target="_blank" rel="noopener" href="${s.url}"><b>${esc(s.name)}</b><span>${esc(s.type)}</span><small>${esc(s.url)}</small></a>`).join("")}
function renderHierarchy(){if(!REG)return;const level=el("level")?.value||"provinsi";let html=Object.entries(REG.kabupaten_kota).map(([id,k])=>{const kids=Object.entries(REG.kecamatan).filter(([,x])=>x.parent_id===id);const active=level==="kabupaten_kota"&&el("region")?.value===id;return`<details ${active?"open":""}><summary><b>${esc(k.name)}</b><span>${kids.length} kecamatan</span></summary><div class="tree-kids">${kids.map(([cid,x])=>`<button class="tree-item" data-level="kecamatan" data-id="${cid}"><b>${esc(x.name)}</b><small>${x.expected_village_count} desa/kelurahan</small></button>`).join("")}</div></details>`}).join("");el("hierarchy").innerHTML=html+`<div class="hierarchy-foot">BPS MFD 2025: 6 kabupaten/kota · 77 kecamatan · 732 wilayah setingkat desa/kelurahan. Detail nama/polygon desa tersedia dari boundary service saat service dapat diakses.</div>`;document.querySelectorAll(".tree-item").forEach(b=>b.onclick=()=>{el("level").value="kecamatan";updateRegionOptions();el("region").value=b.dataset.id;render()})}
document.addEventListener("DOMContentLoaded",load);
