const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const qs=new URLSearchParams(location.search);const LEVEL=qs.get('level')||'provinsi',ID=qs.get('id')||'75';let DATA,REG,SETS,ADMIN=[];
async function get(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${u}`);return r.json()}
function lvl(l){return l==='provinsi'?'Provinsi':l==='kabupaten_kota'?'Kabupaten/Kota':l==='kecamatan'?'Kecamatan':'Desa/Kelurahan'}
function nameOf(){if(LEVEL==='provinsi')return 'Provinsi Gorontalo';if(LEVEL==='kabupaten_kota')return REG.kabupaten_kota[ID]?.name||ID;if(LEVEL==='kecamatan')return REG.kecamatan[ID]?.name||ID;return ADMIN.find(x=>x.code===ID)?.name||ID}
function parent(){if(LEVEL==='kabupaten_kota')return REG.kabupaten_kota[ID]?.name||'';if(LEVEL==='kecamatan')return REG.kabupaten_kota[REG.kecamatan[ID]?.parent_id]?.name||'';if(LEVEL==='desa'){const k=ADMIN.find(x=>x.code===ID.slice(0,-5));return k?.name||''}return '—'}
function finance(){if(LEVEL==='kabupaten_kota'){const r=DATA.regions.find(x=>x.id===ID);return r?`<div class="finance-card"><b>TKDD 2024</b><div class="finance-big">${money(r.realization_million*1e6)}</div><span>Realisasi ${r.realization_pct}% dari anggaran ${money(r.budget_million*1e6)}</span><a href="${esc(r.source)}" target="_blank" rel="noopener">Buka DJPK ↗</a></div>`:'<div class="empty-note">Data TKDD untuk wilayah ini belum ada pada snapshot.</div>'}if(LEVEL==='provinsi'){const p=DATA.province?.apbd||{},a=p['2026']?.initial,b=p['2026']?.latest_change;return `<div class="finance-grid"><div class="finance-card"><b>APBD 2026 Pendapatan Awal</b><div class="finance-big">${money(a?.pendapatan?.total)}</div></div><div class="finance-card"><b>APBD 2026 Belanja Awal</b><div class="finance-big">${money(a?.belanja?.total)}</div></div><div class="finance-card"><b>APBD-P 2026 Belanja Terbaru</b><div class="finance-big">${money((b?.belanja||0)*1e9)}</div></div></div>`}return `<div class="empty-note"><b>Belum ada angka keuangan scoped.</b><br>V3.2 tidak menyalin angka parent ke ${lvl(LEVEL).toLowerCase()}. Cari dataset yang memang memiliki scope ${lvl(LEVEL).toLowerCase()}.</div>`}
function datasets(){const n=nameOf().toLowerCase();const out=SETS.filter(d=>{const h=`${d.title} ${d.category} ${d.owner} ${d.depth}`.toLowerCase();if(LEVEL==='desa'||LEVEL==='kecamatan')return d.depth.toLowerCase().includes('desa')||h.includes('penduduk')||h.includes('umkm');return true}).filter(d=>d.relevant_keywords.some(k=>n.includes(k.toLowerCase()))||d.depth.toLowerCase().includes(LEVEL==='desa'?'desa':LEVEL==='kecamatan'?'desa':'kabupaten'));const unique=[...new Map(out.map(x=>[x.id,x])).values()];return unique.length?unique.slice(0,30):SETS.slice(0,12)}
function children(){if(LEVEL==='provinsi')return Object.entries(REG.kabupaten_kota).map(([id,x])=>({level:'kabupaten_kota',id,name:x.name,sub:`${x.children?.length||0} kecamatan`}));if(LEVEL==='kabupaten_kota')return Object.entries(REG.kecamatan).filter(([,x])=>x.parent_id===ID).map(([id,x])=>({level:'kecamatan',id,name:x.name,sub:`${x.expected_village_count} desa/kelurahan`}));if(LEVEL==='kecamatan')return ADMIN.filter(x=>(x.type==='desa'||x.type==='kelurahan')&&x.code.startsWith(ID+'.')).map(x=>({level:'desa',id:x.code,name:x.name,sub:x.type}));return []}
async function main(){try{[DATA,REG,SETS]=await Promise.all([get('./data/public-data.json'),get('./data/regions.json'),get('./data/datasets.json')]);try{ADMIN=await get('https://unpkg.com/administratif-indonesia@0.2.0/storages/75-gorontalo.json')}catch(e){ADMIN=[]}$('regionTitle').textContent=nameOf();$('regionSubtitle').textContent=`${lvl(LEVEL)} · ${ID} · parent: ${parent()}`;$('regionStatus').textContent='READY';$('regionProfile').innerHTML=`<div><span>Level</span><b>${lvl(LEVEL)}</b></div><div><span>Kode</span><b>${esc(ID)}</b></div><div><span>Parent</span><b>${esc(parent())}</b></div><div><span>Sumber struktur</span><b>BPS / snapshot wilayah</b></div>`;$('regionFinance').innerHTML=finance();$('regionDatasets').innerHTML=datasets().map(d=>`<a class="dataset-card" href="${esc(d.url)}" target="_blank" rel="noopener"><b>${esc(d.title)}</b><span>${esc(d.category)} · ${esc(d.depth)}</span><small>${esc(d.owner)} · diperbarui ${esc(d.updated||'—')}</small><em>Buka dataset asli ↗</em></a>`).join('');$('regionChildren').innerHTML=children().map(x=>`<a class="child-card" href="./region.html?level=${x.level}&id=${encodeURIComponent(x.id)}"><b>${esc(x.name)}</b><span>${esc(x.sub)}</span></a>`).join('')||'<div class="empty-note">Tidak ada subwilayah pada level ini.</div>';$('regionSources').innerHTML=`<p><b>Aturan data:</b> hanya data yang scope-nya sesuai yang diberi label sebagai data wilayah. Dataset Open Data Gorontalo menyediakan format XLSX/CSV/JSON pada halaman dataset dan beberapa dataset memiliki kedalaman Desa/Kelurahan. cite internal</p><p><a href="https://opendata.gorontaloprov.go.id/dataset" target="_blank" rel="noopener">Buka katalog Open Data Gorontalo ↗</a> · <a href="https://gorontalo.bps.go.id/id/publication/2026/03/31/fff77cc651cc3a5df7ba7dbd/master-file-desa-provinsi-gorontalo-2025.html" target="_blank" rel="noopener">BPS Master File Desa 2025 ↗</a></p>`}catch(e){$('regionStatus').textContent='ERROR';$('regionSources').textContent=e.message}}
main();
